"use client";
import {useEffect,useState} from 'react';
import {PageHeading} from '@/components/ui';
import {notificationEvents,notificationChannels} from '@/lib/security';
type Preference={event_type:string;channel:string;enabled:boolean};
type Notice={id:string;title:string;body:string;read_at:string|null};
const labels:Record<string,string>={new_review:'Nieuwe review',negative_review:'Negatieve review',review_reply_ready:'Reviewantwoord klaar',content_ready:'Content klaar',content_published:'Content gepubliceerd',content_failed:'Publicatie mislukt',email_campaign_completed:'E-mailcampagne afgerond',integration_disconnected:'Koppeling verbroken',new_conversation:'Nieuw gesprek in Inbox',payment_failed:'Betaling mislukt',subscription_changed:'Abonnement gewijzigd',security_alert:'Beveiligingsmelding'};
export default function NotificationsPage(){const [preferences,setPreferences]=useState<Preference[]>([]),[notices,setNotices]=useState<Notice[]>([]),[channels,setChannels]=useState<Record<string,string>>({}),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
async function load(){const r=await fetch('/api/notifications',{cache:'no-store'});const b=await r.json();if(!r.ok)throw Error(b.error);setPreferences(b.preferences);setNotices(b.notifications);setChannels(b.channels);}
useEffect(()=>{load().catch(e=>setMessage(e.message));},[]);
async function update(body:unknown){setBusy(true);try{const r=await fetch('/api/notifications',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const b=await r.json();if(!r.ok)throw Error(b.error);await load();setMessage('Opgeslagen.');}catch(e){setMessage(e instanceof Error?e.message:'Opslaan mislukt.');}finally{setBusy(false);}}
return <><PageHeading eyebrow="OP JOUW MANIER" title="Meldingen" description="Beheer je meldingen en voorkeuren per kanaal."/><section className="panel account-panel"><h2>Meldingen ({notices.filter(n=>!n.read_at).length} ongelezen in deze lijst)</h2><button disabled={busy} className="button secondary" onClick={()=>update({action:'read'})}>Alles als gelezen markeren</button>{notices.length===0&&<p>Je hebt nog geen meldingen.</p>}{notices.map(n=><div className="notification-row" key={n.id}><div><h3>{n.title}</h3><p>{n.body}</p></div>{!n.read_at&&<button disabled={busy} className="button secondary" onClick={()=>update({action:'read',id:n.id})}>Gelezen</button>}</div>)}</section><section className="panel account-panel"><h2>Voorkeuren</h2>{notificationEvents.map(event=><div className="notification-row" key={event}><h3>{labels[event]}</h3><div>{notificationChannels.map(channel=><label key={channel} style={{display:'block'}}><input type="checkbox" disabled={busy||!channels[channel]} checked={preferences.some(p=>p.event_type===event&&p.channel===channel&&p.enabled)} onChange={e=>update({action:'preference',event_type:event,channel,enabled:e.target.checked})}/>{channel==='IN_APP'?'In Mavix':channel}{channels[channel]==='setup_required'?' — configuratie vereist':''}</label>)}</div></div>)}</section><p role="status">{message}</p></>;}
