import {NextResponse} from 'next/server';
import {randomBytes} from 'node:crypto';
import {z} from 'zod';
import {workspace,identity,sameOrigin,failure,HttpError,limited,audit} from '@/lib/server/access';
import {adminClient,appUrl} from '@/lib/server/supabase';
import {hash} from '@/lib/server/crypto';
import {emailProvider} from '@/lib/server/notifications';
export async function GET(){try{const {db,workspaceId}=await workspace(['OWNER','ADMIN']);const {data,error}=await db.from('workspace_members').select('user_id,role,created_at').eq('workspace_id',workspaceId);if(error)throw error;return NextResponse.json({members:data});}catch(e){return failure(e);}}
export async function POST(request:Request){try{sameOrigin(request);const body=await request.json();if(body.action==='accept'){const {user}=await identity();const token=z.string().min(40).max(100).parse(body.token);const {error}=await adminClient().rpc('accept_invitation',{p_hash:hash(token),p_user:user.id,p_email:user.email?.toLowerCase()});if(error)throw new HttpError(400,'Uitnodiging ongeldig, verlopen of niet voor dit account.');return NextResponse.json({ok:true});}const auth=await workspace(['OWNER']);await limited('invites:'+auth.user.id,5);const input=z.object({email:z.string().email().transform(v=>v.toLowerCase()),role:z.enum(['ADMIN','MEMBER'])}).parse(body);if(!process.env.EMAIL_API_KEY)throw new HttpError(503,'Uitnodigingen vereisen eerst e-mailconfiguratie.');const token=randomBytes(32).toString('base64url');const {data,error}=await adminClient().from('workspace_invites').insert({workspace_id:auth.workspaceId,email:input.email,role:input.role,token_hash:hash(token),expires_at:new Date(Date.now()+7*86400000).toISOString()}).select('id').single();if(error)throw error;await emailProvider.send(input.email,'Uitnodiging voor Mavix',`Je bent uitgenodigd voor een Mavix-werkruimte. Log in of registreer en open: ${appUrl()}/account/team?invite=${token}`,data.id);await audit(auth.workspaceId,auth.user.id,'member_invited');return NextResponse.json({ok:true});}catch(e){if(e instanceof z.ZodError)return failure(new HttpError(400,'Controleer e-mailadres en rol.'));return failure(e);}}
