import {NextResponse} from 'next/server';
import {workspace,failure,HttpError,sameOrigin,limited} from '@/lib/server/access';
import {emptyWorkspace} from '@/lib/storage';
import {applyContactUnsubscribes,contactConsentGuard,syncNewsletterContacts} from '@/lib/server/newsletter';
import type {Contact} from '@/lib/types';
import {brandProfileSchema,brandAssetsValid} from '@/lib/server/brand-validation';
import {z} from 'zod';
// Newsletter signups are merged into the stored contacts when the workspace is
// loaded (syncNewsletterContacts); saves keep unsubscribes and suppressions in
// step with the Contacts module.
export async function GET(){try{const {db,user,workspaceId,role}=await workspace();const {data,error}=await db.from('business_profiles').select('data,version').eq('workspace_id',workspaceId).single();if(error)throw new HttpError(503,'Werkruimte laden is niet gelukt.');const synced=await syncNewsletterContacts(workspaceId,data.data||{},data.version);const {data:personal,error:profileError}=await db.from('profiles').select('full_name,first_name,last_name,phone,photo').eq('id',user.id).single();if(profileError)throw new HttpError(503,'Profiel laden is niet gelukt.');const empty=structuredClone(emptyWorkspace);empty.contacts=[];empty.library=[];if(empty.review)empty.review.reviews=[];const value={...empty,...synced.data,profile:{...empty.profile,...synced.data.profile},account:{...empty.account,firstName:personal.first_name||personal.full_name||'',lastName:personal.last_name,phone:personal.phone,photo:personal.photo,email:user.email||''},integrations:empty.integrations};return NextResponse.json({data:value,version:synced.version,role,draftScope:workspaceId+":"+user.id},{headers:{'Cache-Control':'no-store'}});}catch(e){return failure(e);}}
export async function PUT(request:Request){try{sameOrigin(request);const {db,workspaceId,user}=await workspace(['OWNER','ADMIN']);await limited('save:'+user.id,60);const text=await request.text();if(text.length>5_000_000)throw new HttpError(413,'Deze werkruimte is te groot.');const {data,version}=z.object({version:z.number().int().nonnegative(),data:z.object({profile:z.object({name:z.string().max(160)}).passthrough(),posts:z.array(z.object({id:z.string(),status:z.enum(['draft','approved','scheduled','rejected','blocked','failed','published'])}).passthrough()).max(10000)}).passthrough()}).parse(JSON.parse(text));const {data:previous,error:previousError}=await db.from('business_profiles').select('data').eq('workspace_id',workspaceId).single();if(previousError)throw previousError;const oldPosts=previous.data?.posts||[];if(data.posts.some(p=>p.status==='published'&&!oldPosts.some((old:{id:string;status:string})=>old.id===p.id&&old.status==='published')))throw new HttpError(409,'Publiceren vereist een echte provideractie. Er is niets gepubliceerd.');
 // Brand Hub: structured fields and images (PNG/JPEG/WebP data URLs only, size-limited).
 const profile=brandProfileSchema.parse(data.profile);
 if(!brandAssetsValid(profile,previous.data?.profile||{}))throw new HttpError(400,'Ongeldige afbeelding. Gebruik een PNG-, JPG- of WebP-bestand binnen de uploadlimiet.');
 const before=(Array.isArray(previous.data?.contacts)?previous.data.contacts:[]) as Contact[],after=(Array.isArray(data.contacts)?data.contacts:[]) as Contact[];
 // Refuse re-subscribing suppressed addresses; record new unsubscribes first.
 await contactConsentGuard(workspaceId,before,after);await applyContactUnsubscribes(workspaceId,before,after);
 delete data.account;delete data.integrations;delete data.notifications;const {data:updated,error}=await db.from('business_profiles').update({data,version:version+1,updated_at:new Date().toISOString()}).eq('workspace_id',workspaceId).eq('version',version).select('version').maybeSingle();if(error)throw new HttpError(503,'Opslaan is niet gelukt.');if(!updated)throw new HttpError(409,'De werkruimte is elders gewijzigd. Herlaad voor je opnieuw opslaat.');return NextResponse.json(updated);}catch(e){if(e instanceof z.ZodError)return failure(new HttpError(400,'Ongeldige werkruimtegegevens.'));return failure(e);}}
