import {oauthStateMatches} from '@/lib/security';
import {NextResponse} from 'next/server';
import {randomBytes} from 'node:crypto';
import {cookies} from 'next/headers';
import {z} from 'zod';
import {workspace,sameOrigin,limited,audit,failure,HttpError} from '@/lib/server/access';
import {adminClient,appUrl} from '@/lib/server/supabase';
import {hash,encrypt,decrypt} from '@/lib/server/crypto';
import {scopes,callback,googleToken,businessLocations,sendTestEmail,type Provider} from '@/lib/server/integrations';
import {cleanupCalendar} from '@/lib/server/calendar';
import {authorizeUrl,completeInstagram,completeMessenger,connectWhatsApp,listPages,metaConfigured,metaScopes,selectPage,type MetaCredentials} from '@/lib/server/meta';
import {GMAIL_READ_SCOPE} from '@/lib/server/inbox';
const testEmailInput=z.object({to:z.string().email().max(254),subject:z.string().trim().min(1).max(200),body:z.string().trim().min(1).max(5000)});
const whatsappInput=z.object({phoneNumberId:z.string().regex(/^\d{5,30}$/),wabaId:z.string().regex(/^\d{5,30}$/),token:z.string().min(20).max(1000).regex(/^[\w.\-|]+$/)});
const PROVIDERS=["google_business","gmail","instagram","google_calendar","messenger","whatsapp"];
const GOOGLE=['google_business','gmail','google_calendar'];
// Optional Google scopes: Gmail can still send without read access; the Inbox
// then shows "Nieuwe toestemming vereist".
const OPTIONAL=[GMAIL_READ_SCOPE];
type Context={params:Promise<{provider:string;action:string}>};
const back=(query:string)=>NextResponse.redirect(new URL('/account/integraties?'+query,appUrl()));
async function newState(provider:string,workspaceId:string,userId:string){const state=randomBytes(32).toString('base64url'),verifier=randomBytes(48).toString('base64url');const {error}=await adminClient().from('oauth_states').insert({token_hash:hash(state),workspace_id:workspaceId,user_id:userId,provider,verifier,expires_at:new Date(Date.now()+600000).toISOString()});if(error)throw error;(await cookies()).set('mavix_oauth_'+provider,state,{httpOnly:true,secure:appUrl().startsWith('https:'),sameSite:'lax',path:'/',maxAge:600});return {state,verifier};}
export async function POST(request:Request,{params}:Context){try{sameOrigin(request);const route=await params; if(!PROVIDERS.includes(route.provider))throw new HttpError(404,"Niet gevonden."); const provider=route.provider as Provider|'messenger'|'whatsapp', action=route.action;const auth=await workspace(['OWNER','ADMIN']);await limited('oauth:'+auth.user.id,10);const db=adminClient();
if(action==='connect'){
 if(provider==='instagram'||provider==='messenger'){if(!metaConfigured(provider))throw new HttpError(503,(provider==='instagram'?'Instagram':'Messenger')+'-koppeling vereist nog Meta-appconfiguratie.');const {state}=await newState(provider,auth.workspaceId,auth.user.id);return NextResponse.json({url:authorizeUrl(provider,state)});}
 if(provider==='whatsapp'){if(!metaConfigured('whatsapp'))throw new HttpError(503,'WhatsApp-koppeling vereist nog Meta-appconfiguratie.');await limited('whatsapp-connect:'+auth.workspaceId,5);const input=whatsappInput.parse(await request.json());const number=await connectWhatsApp(input);const {error}=await db.from('integration_connections').upsert({workspace_id:auth.workspaceId,provider:'whatsapp',connected_user:auth.user.id,provider_account_id:input.phoneNumberId,display_name:number.display+(number.phone?' ('+number.phone+')':''),status:'connected',encrypted_credentials:encrypt({access_token:input.token,obtained_at:Date.now()},auth.workspaceId+':whatsapp'),scopes:['whatsapp_business_messaging','whatsapp_business_management'],expires_at:null,metadata:{wabaId:input.wabaId}},{onConflict:'workspace_id,provider'});if(error)throw error;await audit(auth.workspaceId,auth.user.id,'integration_connected');return NextResponse.json({ok:true});}
 if(!process.env.GOOGLE_CLIENT_ID||!process.env.GOOGLE_CLIENT_SECRET||!process.env.OAUTH_ENCRYPTION_KEY)throw new HttpError(503,'Google-koppeling vereist configuratie.');const {state,verifier}=await newState(provider,auth.workspaceId,auth.user.id);const url=new URL('https://accounts.google.com/o/oauth2/v2/auth');url.search=new URLSearchParams({client_id:process.env.GOOGLE_CLIENT_ID,redirect_uri:callback(provider as Provider),response_type:'code',scope:scopes[provider as Provider].join(' '),state,access_type:'offline',prompt:'consent',code_challenge:Buffer.from(hash(verifier),'hex').toString('base64url'),code_challenge_method:'S256'}).toString();return NextResponse.json({url:url.toString()});}
if(action==='disconnect'){if(provider==='google_calendar'){const {data:existing}=await db.from('integration_connections').select('connected_user').eq('workspace_id',auth.workspaceId).eq('provider',provider).maybeSingle();if(existing?.connected_user)await cleanupCalendar(auth.workspaceId,existing.connected_user).catch(()=>{});}const {error}=await db.from('integration_connections').update({status:'disconnected',encrypted_credentials:null,metadata:{},expires_at:null}).eq('workspace_id',auth.workspaceId).eq('provider',provider);if(error)throw error;await audit(auth.workspaceId,auth.user.id,'integration_disconnected');return NextResponse.json({ok:true});}
if(action==='select'&&provider==='google_business'){const body=await request.json();const location=(await businessLocations(auth.workspaceId)).find(l=>l.id===body.location&&l.account===body.account);if(!location)throw new HttpError(403,'Geen toegang tot deze locatie.');const {error}=await db.from('integration_connections').update({metadata:{account:location.account,location:location.id},display_name:location.name,status:'connected'}).eq('workspace_id',auth.workspaceId).eq('provider',provider);if(error)throw error;await audit(auth.workspaceId,auth.user.id,'integration_connected');return NextResponse.json({ok:true});}
if(action==='select'&&provider==='messenger'){const {page}=z.object({page:z.string().regex(/^\d{1,30}$/)}).parse(await request.json());await selectPage(auth.workspaceId,page);await audit(auth.workspaceId,auth.user.id,'integration_connected');return NextResponse.json({ok:true});}
if(action==='send'&&provider==='gmail'){await limited('gmail-send:'+auth.workspaceId,20);const input=testEmailInput.parse(await request.json());const result=await sendTestEmail(auth.workspaceId,input.to,input.subject,input.body);await audit(auth.workspaceId,auth.user.id,'test_email_sent');return NextResponse.json({id:result.id,status:'sent'});}
throw new HttpError(404,'Niet gevonden.');}catch(e){if(e instanceof z.ZodError)return failure(new HttpError(400,'Controleer de ingevoerde gegevens.'));return failure(e);}}
async function consumeState(provider:string,url:URL,auth:{workspaceId:string;user:{id:string}}){const state=url.searchParams.get('state'),jar=await cookies();if(!oauthStateMatches(state,jar.get('mavix_oauth_'+provider)?.value))throw new HttpError(400,'Ongeldige of verlopen autorisatie.');jar.delete('mavix_oauth_'+provider);const {data:rows,error}=await adminClient().from('oauth_states').delete().eq('token_hash',hash(state!)).eq('user_id',auth.user.id).eq('workspace_id',auth.workspaceId).eq('provider',provider).gt('expires_at',new Date().toISOString()).select();if(error||rows?.length!==1)throw new HttpError(400,'Autorisatie is verlopen of al gebruikt.');return rows[0] as {verifier:string};}
export async function GET(request:Request,{params}:Context){try{const route=await params; if(!PROVIDERS.includes(route.provider))throw new HttpError(404,"Niet gevonden."); const provider=route.provider as Provider|'messenger'|'whatsapp', action=route.action;const auth=await workspace(['OWNER','ADMIN']);const db=adminClient();
if(action==='locations'&&provider==='google_business')return NextResponse.json({locations:await businessLocations(auth.workspaceId)});
if(action==='pages'&&provider==='messenger'){const {data:c}=await db.from('integration_connections').select('encrypted_credentials').eq('workspace_id',auth.workspaceId).eq('provider','messenger').maybeSingle();if(!c?.encrypted_credentials)throw new HttpError(409,'Verbind eerst Facebook.');const creds=decrypt<MetaCredentials>(c.encrypted_credentials,auth.workspaceId+':messenger');if(!creds.user_token)throw new HttpError(409,'Verbind Facebook opnieuw om een andere pagina te kiezen.');return NextResponse.json({pages:(await listPages(creds.user_token)).map(p=>({id:p.id,name:p.name}))});}
if(action!=='callback')throw new HttpError(404,'Niet gevonden.');const url=new URL(request.url);
if(provider==='instagram'||provider==='messenger'){
 if(url.searchParams.get('error')){await consumeState(provider,url,auth).catch(()=>{});return back('error=denied&provider='+provider);}
 await consumeState(provider,url,auth);const code=url.searchParams.get('code');if(!code)return back('error=denied&provider='+provider);
 try{
  if(provider==='instagram'){const ig=await completeInstagram(code);const {error}=await db.from('integration_connections').upsert({workspace_id:auth.workspaceId,provider,connected_user:auth.user.id,provider_account_id:ig.accountId,display_name:ig.name,status:'connected',encrypted_credentials:encrypt({access_token:ig.token,obtained_at:Date.now()},auth.workspaceId+':instagram'),scopes:ig.granted,expires_at:new Date(Date.now()+ig.expiresIn*1000).toISOString(),metadata:{}},{onConflict:'workspace_id,provider'});if(error)throw error;await audit(auth.workspaceId,auth.user.id,'integration_authorized');return back('connected=instagram');}
  const fb=await completeMessenger(code);const {error}=await db.from('integration_connections').upsert({workspace_id:auth.workspaceId,provider,connected_user:auth.user.id,provider_account_id:null,display_name:fb.userName,status:'selection_required',encrypted_credentials:encrypt({access_token:fb.userToken,user_token:fb.userToken,obtained_at:Date.now()},auth.workspaceId+':messenger'),scopes:fb.granted.filter((s:string)=>metaScopes.messenger.includes(s)),expires_at:null,metadata:{}},{onConflict:'workspace_id,provider'});if(error)throw error;await audit(auth.workspaceId,auth.user.id,'integration_authorized');
  const pages=await listPages(fb.userToken);if(pages.length===1){await selectPage(auth.workspaceId,pages[0].id);return back('connected=messenger');}
  return back(pages.length?'select=messenger':'error=no_pages&provider=messenger');
 }catch(e){if(e instanceof HttpError&&e.status===403)return back('error=permission&provider='+provider);throw e;}
}
if(!GOOGLE.includes(provider))throw new HttpError(404,'Niet gevonden.');
const {verifier}=await consumeState(provider,url,auth);const code=url.searchParams.get('code');if(!code)throw new HttpError(400,'Toestemming is niet gegeven.');const token=await googleToken({code,grant_type:'authorization_code',redirect_uri:callback(provider as Provider),code_verifier:verifier});const granted=(token.scope||'').split(' ');const missing=scopes[provider as Provider].filter(s=>s.startsWith('https://www.googleapis.com/auth/')&&!OPTIONAL.includes(s)&&!granted.includes(s));if(missing.length){if(provider==='google_calendar')return NextResponse.redirect(new URL('/calendar?calendar_error=permission',appUrl()));throw new HttpError(403,'Benodigde toestemming ontbreekt.');}const who=await fetch('https://openidconnect.googleapis.com/v1/userinfo',{headers:{Authorization:'Bearer '+token.access_token},cache:'no-store'});if(!who.ok)throw new HttpError(502,'Google-account kon niet worden gecontroleerd.');const account=await who.json();let metadata:Record<string,unknown>={};if(provider==='google_calendar'){const {data:existing}=await db.from('integration_connections').select('connected_user,metadata').eq('workspace_id',auth.workspaceId).eq('provider',provider).maybeSingle();if(existing?.connected_user&&existing.connected_user!==auth.user.id)await cleanupCalendar(auth.workspaceId,existing.connected_user).catch(()=>{});else metadata=existing?.metadata||{};}const {error:saveError}=await db.from('integration_connections').upsert({workspace_id:auth.workspaceId,provider,connected_user:auth.user.id,provider_account_id:account.sub,display_name:account.email,status:provider==='google_business'?'selection_required':'connected',encrypted_credentials:encrypt(token,auth.workspaceId+':'+provider),scopes:granted,expires_at:new Date(Date.now()+(token.expires_in||3600)*1000).toISOString(),metadata},{onConflict:'workspace_id,provider'});if(saveError)throw saveError;await audit(auth.workspaceId,auth.user.id,'integration_authorized');return NextResponse.redirect(new URL(provider==='google_calendar'?'/calendar?connected=1':'/account/integraties'+(provider==='gmail'?'?connected=gmail':''),appUrl()));}catch(e){return failure(e);}}
