import {oauthStateMatches} from '@/lib/security';
import {NextResponse} from 'next/server';
import {randomBytes} from 'node:crypto';
import {cookies} from 'next/headers';
import {workspace,sameOrigin,limited,audit,failure,HttpError} from '@/lib/server/access';
import {adminClient,appUrl} from '@/lib/server/supabase';
import {hash,encrypt} from '@/lib/server/crypto';
import {scopes,callback,googleToken,businessLocations,type Provider} from '@/lib/server/integrations';
type Context={params:Promise<{provider:string;action:string}>};
export async function POST(request:Request,{params}:Context){try{sameOrigin(request);const route=await params; if(!["google_business","gmail","instagram"].includes(route.provider))throw new HttpError(404,"Niet gevonden."); const provider=route.provider as Provider, action=route.action;const auth=await workspace(['OWNER','ADMIN']);await limited('oauth:'+auth.user.id,10);if(!['google_business','gmail','instagram'].includes(provider))throw new HttpError(404,'Niet gevonden.');const db=adminClient();if(action==='connect'){if(provider==='instagram')throw new HttpError(503,'Instagram vereist nog Meta-appconfiguratie en implementatievalidatie.');if(!process.env.GOOGLE_CLIENT_ID||!process.env.GOOGLE_CLIENT_SECRET||!process.env.OAUTH_ENCRYPTION_KEY)throw new HttpError(503,'Google-koppeling vereist configuratie.');const state=randomBytes(32).toString('base64url'),verifier=randomBytes(48).toString('base64url');const {error}=await db.from('oauth_states').insert({token_hash:hash(state),workspace_id:auth.workspaceId,user_id:auth.user.id,provider,verifier,expires_at:new Date(Date.now()+600000).toISOString()});if(error)throw error;(await cookies()).set('mavix_oauth_'+provider,state,{httpOnly:true,secure:appUrl().startsWith('https:'),sameSite:'lax',path:'/',maxAge:600});const url=new URL('https://accounts.google.com/o/oauth2/v2/auth');url.search=new URLSearchParams({client_id:process.env.GOOGLE_CLIENT_ID,redirect_uri:callback(provider),response_type:'code',scope:scopes[provider].join(' '),state,access_type:'offline',prompt:'consent',code_challenge:Buffer.from(hash(verifier),'hex').toString('base64url'),code_challenge_method:'S256'}).toString();return NextResponse.json({url:url.toString()});}if(action==='disconnect'){const {error}=await db.from('integration_connections').update({status:'disconnected',encrypted_credentials:null,metadata:{},expires_at:null}).eq('workspace_id',auth.workspaceId).eq('provider',provider);if(error)throw error;await audit(auth.workspaceId,auth.user.id,'integration_disconnected');return NextResponse.json({ok:true});}if(action==='select'&&provider==='google_business'){const body=await request.json();const location=(await businessLocations(auth.workspaceId)).find(l=>l.id===body.location&&l.account===body.account);if(!location)throw new HttpError(403,'Geen toegang tot deze locatie.');const {error}=await db.from('integration_connections').update({metadata:{account:location.account,location:location.id},display_name:location.name,status:'connected'}).eq('workspace_id',auth.workspaceId).eq('provider',provider);if(error)throw error;await audit(auth.workspaceId,auth.user.id,'integration_connected');return NextResponse.json({ok:true});}throw new HttpError(404,'Niet gevonden.');}catch(e){return failure(e);}}
export async function GET(request:Request,{params}:Context){try{const route=await params; if(!["google_business","gmail","instagram"].includes(route.provider))throw new HttpError(404,"Niet gevonden."); const provider=route.provider as Provider, action=route.action;const auth=await workspace(['OWNER','ADMIN']);if(action==='locations'&&provider==='google_business')return NextResponse.json({locations:await businessLocations(auth.workspaceId)});if(action!=='callback'||!['gmail','google_business'].includes(provider))throw new HttpError(404,'Niet gevonden.');const url=new URL(request.url),state=url.searchParams.get('state'),jar=await cookies();if(!oauthStateMatches(state,jar.get('mavix_oauth_'+provider)?.value))throw new HttpError(400,'Ongeldige of verlopen autorisatie.');jar.delete('mavix_oauth_'+provider);const db=adminClient();const {data:rows,error}=await db.from('oauth_states').delete().eq('token_hash',hash(state!)).eq('user_id',auth.user.id).eq('workspace_id',auth.workspaceId).eq('provider',provider).gt('expires_at',new Date().toISOString()).select();if(error||rows?.length!==1)throw new HttpError(400,'Autorisatie is verlopen of al gebruikt.');const code=url.searchParams.get('code');if(!code)throw new HttpError(400,'Toestemming is niet gegeven.');const token=await googleToken({code,grant_type:'authorization_code',redirect_uri:callback(provider),code_verifier:rows[0].verifier});const granted=(token.scope||'').split(' ');const required=scopes[provider].find(s=>s.startsWith('https://www.googleapis.com/auth/'));if(required&&!granted.includes(required))throw new HttpError(403,'Benodigde toestemming ontbreekt.');const who=await fetch('https://openidconnect.googleapis.com/v1/userinfo',{headers:{Authorization:'Bearer '+token.access_token},cache:'no-store'});if(!who.ok)throw new HttpError(502,'Google-account kon niet worden gecontroleerd.');const account=await who.json();const {error:saveError}=await db.from('integration_connections').upsert({workspace_id:auth.workspaceId,provider,connected_user:auth.user.id,provider_account_id:account.sub,display_name:account.email,status:provider==='google_business'?'selection_required':'connected',encrypted_credentials:encrypt(token,auth.workspaceId+':'+provider),scopes:granted,expires_at:new Date(Date.now()+(token.expires_in||3600)*1000).toISOString(),metadata:{}},{onConflict:'workspace_id,provider'});if(saveError)throw saveError;await audit(auth.workspaceId,auth.user.id,'integration_authorized');return NextResponse.redirect(new URL('/account/integraties',appUrl()));}catch(e){return failure(e);}}
